spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/labs
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate:      ddl-auto: validate